/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetRegistry,
  IAssetRegistryInterface,
} from "../../../contracts/interfaces/IAssetRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "fingerprint",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "eligible",
        type: "bool",
      },
    ],
    name: "AssetRegistered",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "fingerprint",
        type: "bytes32",
      },
    ],
    name: "getAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "fingerprint",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "oracleAttestation",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "abmOutputHash",
        type: "bytes32",
      },
      {
        internalType: "uint256[4]",
        name: "scores",
        type: "uint256[4]",
      },
      {
        internalType: "bool",
        name: "eligible",
        type: "bool",
      },
    ],
    name: "registerAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAssetRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetRegistryInterface {
    return new Interface(_abi) as IAssetRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetRegistry {
    return new Contract(address, _abi, runner) as unknown as IAssetRegistry;
  }
}
