/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAssetRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getAsset" | "registerAsset"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AssetRegistered"): EventFragment;

  encodeFunctionData(functionFragment: "getAsset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [
      BytesLike,
      AddressLike,
      BytesLike,
      BytesLike,
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      boolean
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    fingerprint: BytesLike,
    owner: AddressLike,
    eligible: boolean
  ];
  export type OutputTuple = [
    fingerprint: string,
    owner: string,
    eligible: boolean
  ];
  export interface OutputObject {
    fingerprint: string;
    owner: string;
    eligible: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAssetRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAssetRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAsset: TypedContractMethod<
    [fingerprint: BytesLike],
    [[boolean, bigint, bigint]],
    "view"
  >;

  registerAsset: TypedContractMethod<
    [
      fingerprint: BytesLike,
      owner: AddressLike,
      oracleAttestation: BytesLike,
      abmOutputHash: BytesLike,
      scores: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      eligible: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [fingerprint: BytesLike],
    [[boolean, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [
      fingerprint: BytesLike,
      owner: AddressLike,
      oracleAttestation: BytesLike,
      abmOutputHash: BytesLike,
      scores: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      eligible: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(bytes32,address,bool)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
  };
}
