/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AsyncRedemptionController {
  export type RedemptionRequestStruct = {
    investor: AddressLike;
    token: AddressLike;
    tokenAmount: BigNumberish;
    estimatedValue: BigNumberish;
    requestTime: BigNumberish;
    settlementTime: BigNumberish;
    status: BigNumberish;
    proofHash: BytesLike;
  };

  export type RedemptionRequestStructOutput = [
    investor: string,
    token: string,
    tokenAmount: bigint,
    estimatedValue: bigint,
    requestTime: bigint,
    settlementTime: bigint,
    status: bigint,
    proofHash: string
  ] & {
    investor: string;
    token: string;
    tokenAmount: bigint;
    estimatedValue: bigint;
    requestTime: bigint;
    settlementTime: bigint;
    status: bigint;
    proofHash: string;
  };
}

export interface AsyncRedemptionControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "SETTLEMENT_PERIOD"
      | "approveRedemption"
      | "cancelRedemption"
      | "getInvestorRequests"
      | "getRedemptionRequest"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "investorRequests"
      | "pendingRedemptions"
      | "redemptionRequests"
      | "renounceRole"
      | "requestRedemption"
      | "revokeRole"
      | "settleRedemption"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RedemptionApproved"
      | "RedemptionCancelled"
      | "RedemptionRequested"
      | "RedemptionSettled"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SETTLEMENT_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveRedemption",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRedemption",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestorRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRedemptionRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investorRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedemptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRedemption",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleRedemption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SETTLEMENT_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestorRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedemptionRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedemptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace RedemptionApprovedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    settlementValue: BigNumberish
  ];
  export type OutputTuple = [requestId: string, settlementValue: bigint];
  export interface OutputObject {
    requestId: string;
    settlementValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionCancelledEvent {
  export type InputTuple = [requestId: BytesLike, reason: string];
  export type OutputTuple = [requestId: string, reason: string];
  export interface OutputObject {
    requestId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    investor: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    investor: string,
    token: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    investor: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionSettledEvent {
  export type InputTuple = [requestId: BytesLike, actualValue: BigNumberish];
  export type OutputTuple = [requestId: string, actualValue: bigint];
  export interface OutputObject {
    requestId: string;
    actualValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AsyncRedemptionController extends BaseContract {
  connect(runner?: ContractRunner | null): AsyncRedemptionController;
  waitForDeployment(): Promise<this>;

  interface: AsyncRedemptionControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  SETTLEMENT_PERIOD: TypedContractMethod<[], [bigint], "view">;

  approveRedemption: TypedContractMethod<
    [requestId: BytesLike, settlementValue: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelRedemption: TypedContractMethod<
    [requestId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getInvestorRequests: TypedContractMethod<
    [investor: AddressLike],
    [string[]],
    "view"
  >;

  getRedemptionRequest: TypedContractMethod<
    [requestId: BytesLike],
    [AsyncRedemptionController.RedemptionRequestStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  investorRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  pendingRedemptions: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  redemptionRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, string] & {
        investor: string;
        token: string;
        tokenAmount: bigint;
        estimatedValue: bigint;
        requestTime: bigint;
        settlementTime: bigint;
        status: bigint;
        proofHash: string;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRedemption: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  settleRedemption: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SETTLEMENT_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveRedemption"
  ): TypedContractMethod<
    [requestId: BytesLike, settlementValue: BigNumberish, proofHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelRedemption"
  ): TypedContractMethod<
    [requestId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getInvestorRequests"
  ): TypedContractMethod<[investor: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRedemptionRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [AsyncRedemptionController.RedemptionRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "investorRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRedemptions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "redemptionRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, string] & {
        investor: string;
        token: string;
        tokenAmount: bigint;
        estimatedValue: bigint;
        requestTime: bigint;
        settlementTime: bigint;
        status: bigint;
        proofHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRedemption"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleRedemption"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "RedemptionApproved"
  ): TypedContractEvent<
    RedemptionApprovedEvent.InputTuple,
    RedemptionApprovedEvent.OutputTuple,
    RedemptionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionCancelled"
  ): TypedContractEvent<
    RedemptionCancelledEvent.InputTuple,
    RedemptionCancelledEvent.OutputTuple,
    RedemptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionRequested"
  ): TypedContractEvent<
    RedemptionRequestedEvent.InputTuple,
    RedemptionRequestedEvent.OutputTuple,
    RedemptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionSettled"
  ): TypedContractEvent<
    RedemptionSettledEvent.InputTuple,
    RedemptionSettledEvent.OutputTuple,
    RedemptionSettledEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "RedemptionApproved(bytes32,uint256)": TypedContractEvent<
      RedemptionApprovedEvent.InputTuple,
      RedemptionApprovedEvent.OutputTuple,
      RedemptionApprovedEvent.OutputObject
    >;
    RedemptionApproved: TypedContractEvent<
      RedemptionApprovedEvent.InputTuple,
      RedemptionApprovedEvent.OutputTuple,
      RedemptionApprovedEvent.OutputObject
    >;

    "RedemptionCancelled(bytes32,string)": TypedContractEvent<
      RedemptionCancelledEvent.InputTuple,
      RedemptionCancelledEvent.OutputTuple,
      RedemptionCancelledEvent.OutputObject
    >;
    RedemptionCancelled: TypedContractEvent<
      RedemptionCancelledEvent.InputTuple,
      RedemptionCancelledEvent.OutputTuple,
      RedemptionCancelledEvent.OutputObject
    >;

    "RedemptionRequested(bytes32,address,address,uint256,uint256)": TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;
    RedemptionRequested: TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;

    "RedemptionSettled(bytes32,uint256)": TypedContractEvent<
      RedemptionSettledEvent.InputTuple,
      RedemptionSettledEvent.OutputTuple,
      RedemptionSettledEvent.OutputObject
    >;
    RedemptionSettled: TypedContractEvent<
      RedemptionSettledEvent.InputTuple,
      RedemptionSettledEvent.OutputTuple,
      RedemptionSettledEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
